export const metadata = {
  title: "CryptoDashboard Task",
  description: "Generated by MohammadZolghadr",
}

const themeInitScript = `
  try {
    const savedTheme = localStorage.getItem("crypto-dashboard-theme") || "system";
    let resolvedTheme = savedTheme;

    if (savedTheme === "system") {
      resolvedTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
        ? "dark"
        : "light";
    }

    document.documentElement.setAttribute("data-theme", resolvedTheme);
  } catch (e) {
    console.error("Theme init failed", e);
  }
`

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeInitScript }} />
      </head>
      <body>{children}</body>
    </html>
  )
}
